### ISSUE TITLE
Include ipython

### ISSUE THREAD

**Issue by jankatins** [pelson/raspberrypi-conda-recipes#1]
It would be nice to install a up-to-date ipython 3.x on the raspberry pi :-)

**Comment by pelson** [comment]
@JanSchulz - interested in getting involved? Christmas time :christmas_tree: was the motivation for this repository :wink:

**Comment by jankatins** [comment]
@pelson Do you have some intro how to port receipts? Up to now I haven't yet done any conda packaging :-(

**Comment by pelson** [comment]
conda packaging is fairly easy, and shouldn't be too onerous.

First port of call is to look at existing recipes:
- https://github.com/conda/conda-recipes
- https://github.com/SciTools/conda-recipes-scitools
- https://github.com/TheClimateCorporation/conda-recipes
- https://github.com/ioos/conda-recipes
- https://bitbucket.org/abilisoft/pkgs

Happy to provide advise if there is anything I can do.

**Comment by jankatins** [comment]
So in it's easiest form, it's just a merge of a receipt, build on the raspberry pi and upload?

**Comment by pelson** [comment]
Yep, that is about it.
