### ISSUE TITLE
Update for binstar to anaconda conversion

### ISSUE THREAD

**Issue by jakirkham** [pelson/raspberrypi-conda-recipes#2]
- [ ] [recipes/clyent/meta.yaml#L6](https://github.com/pelson/raspberrypi-conda-recipes/blob/8c7b19592e8544b77b8f6d570ca1c3fd644c30e1/recipes/clyent/meta.yaml#L6)
- [ ] [recipes/anaconda-client/meta.yaml#L25](https://github.com/pelson/raspberrypi-conda-recipes/blob/8c7b19592e8544b77b8f6d570ca1c3fd644c30e1/recipes/anaconda-client/meta.yaml#L25)
- [ ] [README.md#L3-L5](https://github.com/pelson/raspberrypi-conda-recipes/blob/8c7b19592e8544b77b8f6d570ca1c3fd644c30e1/README.md#L3-L5)

**Comment by pelson** [comment]
Just checking - is this a reminder to create an conda-server distribution, rather than a binstar one?

**Comment by jakirkham** [comment]
That is a good point, but it probably should be its own issue.

This is regarding the fact that [https://binstar.org](binstar.org) is becoming [https://anaconda.org](anaconda.org).

**Comment by jakirkham** [comment]
It seems there still are a few references. I added them to the issue description with links to their locations.

**Comment by pelson** [comment]
Aha, thanks @jakirkham!

 recipes/anaconda-client/meta.yaml#L25 still points to binstar_client as that is how they have the project importable still: https://github.com/Anaconda-Server/anaconda-client/blob/develop/setup.py

I've fixed the rest in 466b1da.
